language: node_js
node_js:
- 5.6
cache:
  directories:
  - node_modules
  - typings
deploy:
  provider: npm
  email: dave@etianen.com
  api_key:
    secure: "AOIbvvHcUtXsyQUWlB4IClWI2xNe+DEwGF3bIAU9aGg+PR2vajAPPuAPXEZtiv5p1vDK5r+tP181D6UYHIJp2ZGis/4Bbi5Rz6+AmCfeccX032/Qsi+UbMqAK9jZ5z28PoaqA0HblupiszXSzDEWXZExz+NG6xIexh4gFmTPfkmhJoRgKyFZloZ1Qek5+4l5k7JgCyxCAmF5wvxYtyCk4MALltuWF8j3QXgVnbBM7f7M4KUVCMXU42abDGkj0oo2K14cfFuMhaU2i4tQxZOTahkzVQEupyo1i14NZFWLOQQXoCHYTDLZbxK87/2doqOaKFgIR+2EyVTM9l1HYl6tWz1SMAJc1aJoCakbpe+JrVT14GXzNkXkY9dqvzhXq6oiCycIiracS2LjapkuspoGfMR+knPtnygkuPTHOVoCVqSWRGaWNvjw0oNWgA6Nur6yuRfZmNlb9XGkTk3nl2KHSFEE+loo5RTS5SUpagm2qy/3RM4+rBJd3q5yaXr9c77QiAHrddh22JL48GjvQfLlB3mxTBaW+J22Rpd1oGoTYEPhB1PP33rrV/Z4c6OgdrRKehp354WDpkMXA6251TkzvMuI2pmVUm32hWH10FJCCU6m8Ckw/yPd3rANwAc+b7gg/67cOPfO2/+dzz1fGcZhUDZTrlE1c0b2eglaeuk31mk="
  skip_cleanup: true
  on:
    tags: true
    repo: etianen/js-dict
notifications:
  on_success: never
  on_failure: change
